apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lijitijil/ArgocdProject.git
    targetRevision: HEAD
    path: influxdb
  destination: 
    server: https://kubernetes.default.svc
    namespace: influxdbapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  
  


  




