apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto-helm-chart
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RispaJoseph/argocd-app-config.git
    targetRevision: HEAD
    path: mosquitto3
  destination: 
    server: https://kubernetes.default.svc
    namespace: mosquitto

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  
  


  




